
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fubygcvzquqbrpdbycxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YnlnY3Z6cXVxYnJwZGJ5Y3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjMwMjYsImV4cCI6MjA2MzIzOTAyNn0.vRrkE4AAyScOHuJZhZuLdpOQ0j1ygXvxmq5h8Mbc9Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add type declaration for the admin_insert_client function
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    rpc<T = any, P = any>(
      fn: string,
      params?: P,
      options?: { head?: boolean; count?: null | 'exact' | 'planned' | 'estimated' }
    ): Promise<{ data: T; error: null } | { data: null; error: any }>;
  }
}
